### ISSUE TITLE
[APP] token refresh bug outline

### ISSUE THREAD

**Issue by weswalla** [Common-SenseMakers/sensemakers#91] opened 2024-05-31 22:43 UTC
@pepoospina 

The problem:

When the frontend calls the `api/posts/getOfUser` from the `fetchNewer` hook, the backend handles this request. In handling the request, it checks if the twitter token is outdated, and if it is, it refreshes it, then updates the user document with the new tokens.

When the token is outdated, the backend successfully refreshes it, but fails to actually update the user document. This is clear via the logs. For example, I see the following:
```
>  [DEBUG]: getClientWithCredentials - refreshOAuth2Token() 'SUlOYi1iTzFxR2dTX3pKTjNGM09TUy05Nm56RU16c0FrRTQtT0s1N25fYThGOjE3MTcxOTMwNDgzMTI6MTowOnJ0OjE'
>  [DEBUG]: getClientWithCredentials - newCredentials {
>    accessToken: 'Z2FObEQ2SE9FQ3dnMHAzMF80Z0s1TlZYaEdxVmhBLVhtYUZXYVpvXzF2UXJnOjE3MTcxOTMwNzU2NTk6MToxOmF0OjE',
>    refreshToken: 'TFUtZE13X2FBWUJDVG42N0NwRTJuUEtPUEtkSUZRSHpLRjE2S21IdHpDaGtzOjE3MTcxOTMwNzU2NTk6MTowOnJ0OjE',
>    expiresIn: 7200,
>    expiresAtMs: 1717200275680
>  }
```
However, when I check firestore in the emulator suite, the tokens are still the original values that get set when the user logs in (the user document is set / updated in handling the `api/auth/twitter/signup` endpoint).

I believe the issue lies in how the transaction manager writes to the database, but I was unable to determine why.

The way the `handleSignupController` runs the transactions in the manager works fine:
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/users/controllers/platforms.auth.controller.ts#L48-L85

However, the way the `getUserPostsController` runs the transaction manager doesn't work:
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/posts/controllers/posts.controller.ts#L31-L52

drilling it, the call stack goes:
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/posts/controllers/posts.controller.ts#L44
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/posts/posts.manager.ts#L317
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/posts/posts.manager.ts#L288
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/posts/posts.manager.ts#L231-L236
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/posts/posts.manager.ts#L132-L137
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/platforms/platforms.service.ts#L57-L61
https://github.com/Common-SenseMakers/sensemakers/blob/9a2bf8cd028ba2f0ea2943960345a0a6670b3411/app/firebase/functions/src/platforms/twitter/twitter.service.ts#L185
https://github.com/weswalla/sensemakers/blob/d44765aed22b956eac8d63b18eea701fe5795e9b/app/firebase/functions/src/platforms/twitter/twitter.service.ts#L81-L85
```typescript
const readOnlyClient = await this.getUserClient(
        userDetails.user_id,
        'read',
        manager
      );
```
which eventually calls:
https://github.com/weswalla/sensemakers/blob/d44765aed22b956eac8d63b18eea701fe5795e9b/app/firebase/functions/src/platforms/twitter/twitter.service.client.ts#L169-L174
```typescript
await this.usersRepo.setPlatformDetails(
        userId,
        PLATFORM.Twitter,
        newDetails,
        manager
      );
```

where the transactions get run is:
https://github.com/weswalla/sensemakers/blob/d44765aed22b956eac8d63b18eea701fe5795e9b/app/firebase/functions/src/posts/posts.manager.ts#L272
```typescript
return this.db.run((manager) => fetch(manager));
```

I also noticed that there is a comment about the following function not being able to be run as part of a transaction:
https://github.com/Common-SenseMakers/sensemakers/blob/9f76c9e62f3ad41b9961be1a4aeae7b469cc5390/app/firebase/functions/src/posts/posts.manager.ts#L307-L310

And wonder if that has anything to do with it. 

A check that I did was the following:

```typescript
export const getUserPostsController: RequestHandler = async (
  request,
  response
) => {
  try {
    const queryParams = (await getUserPostsQuerySchema.validate(
      request.body
    )) as UserPostsQuery;

    logger.debug(`${request.path} - query parameters`, { queryParams });
    // const userId = getAuthenticatedUser(request, true);
    // const { postsManager, db, users } = getServices(request);
    const { db, users } = getServices(request);

    // const posts = await postsManager.getOfUser(userId, queryParams);

    await db.run(async (manager) => {
      /** handle signup and refetch user posts */
      return await users.repo.setPlatformDetails(
        'twitter:1773032135814717440',
        PLATFORM.Twitter,
        {
          user_id: '1773032135814717440',
          signupDate: 0,
          profile: {
            id: '1773032135814717440',
            username: 'sense_nets_bot',
            profile_image_url:
              'https://pbs.twimg.com/profile_images/1783977034038882304/RGn66lGT_normal.jpg',
            name: 'SenseNet Bot',
          },
          read: {
            accessToken:
              'ZmJLTDFKOUxqcTNEdDM4TkZfbGdLbEw5YnJzSFprVU1SMFFWNDl6MlpZNmhZOjE3MTcxODgzMjg0Nzk6MTowOmF0OjE',
            refreshToken:
              'UGtvcVA2cWRIdWZjM204dkFraEtBazhpb254T3hkMFVhV29XdlhiNXh6M3ZDOjE3MTcxODgzMjg0Nzk6MTowOnJ0OjE',
            expiresIn: 7200,
            expiresAtMs: 1717195528451,
          },
          fetched: {
            newest_id: '1795069204418175459',
            oldest_id: '1781580308069920849',
          },
        },
        manager
      );
    });
    const posts: any[] = [];
    // if (DEBUG) logger.debug(`${request.path}: posts`, { posts, userId });
    response.status(200).send({ success: true, data: posts });
  } catch (error: any) {
    logger.error('error', error);
    response.status(500).send({ success: false, error: error.message });
  }
};
```

Which successfully updated the user document, indicating the `const posts = await postsManager.getOfUser(userId, queryParams);` does not successful run transactions.

**Comment by pepoospina** [comment] 2024-06-01 04:25
Thanks @weswalla I will investigate. Maybe it's the way the transaction manager merges temporary changes in the cache

**Comment by pepoospina** [comment] 2024-06-03 14:48
Hi @weswalla , I was exploring this issue in depth, not so much the cause, but trying to replicate it on a test. 

I updated the test 011 to verify that the refresh token stored on the user profile in the DB is correct. It seems it does. This suggested to me that is not an issue with the Transaction Manager, but maybe I'm missing something.

I then tried to go one step closer and use the actual `getOfUser` method of the posts.manager, but I was not able to configure the test in a way that I could programatically test the value of the refresh token. The outer I can go is the `getUserClientInternal` method.

The first step I think would be to find a test that can show the bug in a reproducible way (hopefully without fetching posts from the real twitter API to not hit the rate limit). I was not able to do this find this reproducible test.

I've pushed my changes to 
https://github.com/pepoospina/sensemakers/tree/refresh-token

You will see the second test of 011 wont pass if you use the mocked twitter API. That's expected as it does not call the getUserClient and thus dont update the user credentials.

One note is that while the first test in 011 passes, Some times it fails with the same error we see in production. This might be our reproducible scenario. While we are not using a DB, we do use a file that is not deleted and stores the latest refresh token. Sometimes this flow breaks andI have to manually delete the file and re-run the test to have it passing again.

I will have to stop the work for today. I'm pushing it in case it can give you more insights on what might be going on.

**Comment by pepoospina** [comment] 2024-06-04 09:41
Hi @weswalla , I finally found the issue. It was indeed related to the transaction manager. Good catch.

The issue is that the transaction manager has a `manager.query` method which is not aware of the cached changes (mutations) in the manager. 

When getting the users posts, after we updated the user account with the new credentials, we also wanted to update the `fetched` data of that user account. For this, we use `setAccountFetched` in the `users.repository` which first read that user using a query (because we had the platform id and not the userId) and this query was getting the old user data and not the just updated (within the same transaction) data. 

This second update would then set the `fetched` properties but overwrite the previous update that had the new credentials, leaving the old credentials as the final ones.

What I did to fix it was to limit the query method (`getUserWithPlatformAccount`) to only return the `userId` string, and then use `manager.get` to get the the user full data. `manager.get` is aware of cached changes and thus the `fetched` change is done on top of the `read` credentials change.

I took the time to change this on every instance we use manager.query (just 4)

This makes issues with `manager.query` less likely, but not zero. We still don't support cases where the result of the query should be different based on cached mutations. This would be much harder to implement as we should support any type of query, at least in principle.

I merged and pushed to `development` and will merge into my work on edit post, and will check all tests pass there.

**Comment by weswalla** [comment] 2024-06-04 18:29
great, thanks for the overview @pepoospina! this is useful to know for working with the transaction manager and being aware of its current limitations.

Just noting the relevant commit for future reference: https://github.com/Common-SenseMakers/sensemakers/commit/8a0dfdf76a0ae8a1d095e7bc85aebc6c04941393

**Closed** 2024-06-04 18:29 UTC
